CREATE TABLE public.drawer_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  icon TEXT NOT NULL,
  route TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Comentario para describir la tabla
COMMENT ON TABLE public.drawer_items IS 'Almacena los ítems de navegación para el Drawer de la aplicación.';
